2023-11-10 11:58:41,024 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 11:59:13,920 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 11:59:23,858 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 12:19:28,225 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 12:19:41,518 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:11:48,896 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:12:31,140 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:13:47,592 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:23:05,516 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:23:07,490 ERROR: Exception on /index [GET] [in /home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/can/Documents/GitHub/flask-example/microblog/app/routes.py", line 21, in index
    posts = current_user.followed_posts().paginate(page=page, per_page=app.config[POSTS_PER_PAGE], error_out=False)
NameError: name 'POSTS_PER_PAGE' is not defined
2023-11-10 13:23:10,425 ERROR: Exception on /index [GET] [in /home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/can/Documents/GitHub/flask-example/microblog/app/routes.py", line 21, in index
    posts = current_user.followed_posts().paginate(page=page, per_page=app.config[POSTS_PER_PAGE], error_out=False)
NameError: name 'POSTS_PER_PAGE' is not defined
2023-11-10 13:23:11,470 ERROR: Exception on /index [GET] [in /home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/can/Desktop/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/can/Documents/GitHub/flask-example/microblog/app/routes.py", line 21, in index
    posts = current_user.followed_posts().paginate(page=page, per_page=app.config[POSTS_PER_PAGE], error_out=False)
NameError: name 'POSTS_PER_PAGE' is not defined
2023-11-10 13:24:06,367 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:27:34,436 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:27:56,335 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:28:21,446 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:28:37,200 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:28:49,972 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:32:50,986 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
2023-11-10 13:34:34,321 INFO: Microblog startup [in /home/can/Documents/GitHub/flask-example/microblog/app/__init__.py:41]
